apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: robinhoodis/ubuntu:0.1.0
    command:
      - "sleep"
      - "9999"
    imagePullPolicy: Always
    name: ubuntu
  restartPolicy: Always
