apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: robinhoodis/ubuntu:0.0.9
    command:
      - "sleep"
      - "0.0.90"
    imagePullPolicy: Always
    name: ubuntu
  restartPolicy: Always
